print("Check if a set is a subset of another set")
setx = set(["apple", "mango"])
sety = set(["mango", "orange"])
setz = set(["mango"])
print("x: ",setx)
print("y: ",sety)
print("z: ",setz)
print("If x is subset of y")
print(setx <= sety)
print(setx.issubset(sety))
print("If x is subset of z")
print(setx <= setz)
print(setx.issubset(setz))
print("If y is subset of x")
print(sety <= setx)
print(sety.issubset(setx))
print("If y is subset of z")
print(sety <= setz)
print(sety.issubset(setz))
print("If z is subset of y")
print(setz <= sety)
print(setz.issubset(sety))
print("If z is subset of x")
print(setz <= setx)
print(setz.issubset(setx))
